### ISSUE TITLE
`pip install .` fails to install `_network.so`

### ISSUE THREAD

**Issue by mgedmin** [linkcheck/linkchecker#13]
Steps to reproduce:
- git clone https://github.com/linkcheck/linkchecker && cd linkchecker
- virtualenv /tmp/env
- /tmp/env/bin/pip install .
- /tmp/env/bin/pip install requests
- /tmp/env/bin/python -c 'import linkcheck.network'

Expected result:
- import succeeds

Actual result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "linkcheck/network/__init__.py", line 10, in <module>
    from ._network import ifreq_size
ImportError: No module named _network
```

**Comment by mgedmin** [comment]
TBH I don't know what the `_network` module is used for, but the test suite tries to import it, and this bug prevents `tox` from working correctly in a clean checkout.

(As a workaround you can run `make localbuild` before you do the `pip install .` step and the `_network.so` module will be copied over.)

**Comment by mgedmin** [comment]
I was mistaken: if I check with `ls`, the `site-packages/linkcheck/network/_network.so` file is there.  It's just the import that fails.

**Comment by mgedmin** [comment]
... and it fails because I was running the `~/tmp/env/bin/python -c 'import ...'` at the top of a git checkout, and Python finds and loads `./linkcheck/network` (which nas no `_network.so`) instead of `~/tmp/env/lib/pythonX.Y/site-packages/linkcheck/network` (with the `_network.so`)!

This is one of the reasons why many Python packages put all the source files into a `src/` subdirectory at the project root.

**Comment by mgedmin** [comment]
Closing as invalid.
