### ISSUE TITLE
ImportError: No module named _network

### ISSUE THREAD

**Issue by fengshuai198904** [linkcheck/linkchecker#25]
$ ./linkchecker/linkchecker https://www.baidu.com
Traceback (most recent call last):
  File "./linkchecker/linkchecker", line 36, in <module>
    from linkcheck.cmdline import print_version, print_usage, aggregate_url, \
  File "/home/admin/fengshuai/linkchecker/linkcheck/cmdline.py", line 23, in <module>
    from . import checker, fileutil, strformat, plugins
  File "/home/admin/fengshuai/linkchecker/linkcheck/checker/__init__.py", line 178, in <module>
    from . import (fileurl, unknownurl, ftpurl, httpurl, dnsurl,
  File "/home/admin/fengshuai/linkchecker/linkcheck/checker/fileurl.py", line 36, in <module>
    from . import urlbase, get_index_html
  File "/home/admin/fengshuai/linkchecker/linkcheck/checker/urlbase.py", line 46, in <module>
    from ..network import iputil
  File "/home/admin/fengshuai/linkchecker/linkcheck/network/__init__.py", line 10, in <module>
    from ._network import ifreq_size
ImportError: No module named _network

**Comment by anarcat** [comment]
@fengshuai198904 why do you keep on submitting issues and then closing them?
