### ISSUE TITLE
Error when trying to install linkchecker with python 3.6

### ISSUE THREAD

**Issue by fhightower** [linkcheck/linkchecker#59]
# Version Numbers:

```
$ python3 --version
Python 3.6.0
$ pip3 -V
pip 9.0.1 from ... (python 3.6)
```

# Attempted Installation:

```
$ pip3 install linkchecker
```

# Error:

```
Collecting linkchecker
  Using cached LinkChecker-9.3.tar.gz
Requirement already satisfied: requests>=2.2.0 in /usr/local/lib/python3.6/site-packages (from linkchecker)
Building wheels for collected packages: linkchecker
  Running setup.py bdist_wheel for linkchecker ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpoaxzn3bipip-wheel- --python-tag cp36:
  /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'app'
    warnings.warn(msg)
  creating /private/tmp/pip-build-cpdcjupz/linkchecker/_LinkChecker_configdata.py
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 976, in <module>
      setup(**args)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 476, in run_commands
      super(MyDistribution, self).run_commands()
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 601, in run
      check_manifest()
    File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 574, in check_manifest
      manifest = [l.strip() for l in f.readlines() if not l.startswith('#')]
    File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1159: ordinal not in range(128)
  
  ----------------------------------------
  Failed building wheel for linkchecker
  Running setup.py clean for linkchecker
Failed to build linkchecker
Installing collected packages: linkchecker
  Running setup.py install for linkchecker ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5lp6tgn-record/install-record.txt --single-version-externally-managed --compile:
    /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'app'
      warnings.warn(msg)
    creating /private/tmp/pip-build-cpdcjupz/linkchecker/_LinkChecker_configdata.py
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 976, in <module>
        setup(**args)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 476, in run_commands
        super(MyDistribution, self).run_commands()
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 601, in run
        check_manifest()
      File "/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py", line 574, in check_manifest
        manifest = [l.strip() for l in f.readlines() if not l.startswith('#')]
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1159: ordinal not in range(128)
    
    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cpdcjupz/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-c5lp6tgn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-cpdcjupz/linkchecker/
```

**Comment by anarcat** [comment]
can you try again with a C.UTF-8 locale?

**Comment by mgedmin** [comment]
linkchecker hasn't been ported to Python 3 yet, see #40.

**Comment by fhightower** [comment]
Ok, thanks for the help.
