### ISSUE TITLE
301 redirect, http to https, causes AttributeError: 'NoneType' object has no attribute 'sock'

### ISSUE THREAD

**Issue by jdgoettsch** [linkcheck/linkchecker#73]
I'm using 4a092c218cd1c64cfe44b448b5f84d66356cf7ac cloned from git.

My `linkcheckerrc` contains:

```init
ignore=
  ^mailto:
  xmlrpc.php$
```

`$ linkchecker --check-extern https://gifford.ucdavis.edu`
```python
...
********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-http://get.adobe.com/reader/, started 4440285184)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://get.adobe.com/reader/, started 4440285184)>>
      url_data = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x10668e758>
      url_data = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self = <local> <Checker(CheckThread-http://get.adobe.com/reader/, started 4440285184)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x107a44350>
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>>
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/urlbase.py", line 439, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/r...
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/urlbase.py", line 457, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe....
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/httpurl.py", line 149, in check_connection
    line: self.follow_redirections(request)
    locals:
      self = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self.follow_redirections = <local> <bound method HttpUrl.follow_redirections of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.ado...
      request = <local> <PreparedRequest [GET]>
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/httpurl.py", line 276, in follow_redirections
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com...
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/httpurl.py", line 206, in _add_ssl_info
    line: sock = self._get_ssl_sock()
    locals:
      sock = <not found>
      self = <local> <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com/reader/>
      self._get_ssl_sock = <local> <bound method HttpUrl._get_ssl_sock of <https link, base_url=u'http://get.adobe.com/reader/', parent_url=u'https://gifford.ucdavis.edu/site-help/', base_ref=None, recursion_level=2, url_connection=None, line=22, column=1734, page=0, name=u'Adobe Reader', anchor=u'', cache_url=http://get.adobe.com...
  File "/Users/jeff/.virtualenvs/linkchecker-launchd/lib/python2.7/site-packages/LinkChecker-9.4-py2.7-macosx-10.10-x86_64.egg/linkcheck/checker/httpurl.py", line 197, in _get_ssl_sock
    line: if raw_connection.sock is None:
    locals:
      raw_connection = <local> None
      raw_connection.sock = <local> !AttributeError: 'NoneType' object has no attribute 'sock'
      None = <builtin> None
AttributeError: 'NoneType' object has no attribute 'sock'
System info:
LinkChecker 9.4
Released on: xx.xx.xxxx
Python 2.7.13 (default, Apr 23 2017, 16:50:46)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Modules: Requests, Pysqlite, Sqlite
Local time: 2017-06-19 10:36:23-007
sys.argv: ['/Users/jeff/.virtualenvs/linkchecker-launchd/bin/linkchecker', '--check-extern', 'https://gifford.ucdavis.edu']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2017-06-19 10:36:23,613 CheckThread-http://get.adobe.com/reader/ internal error occurred
...```

**Comment by jdgoettsch** [comment]
The issue was identified in #76.
