### ISSUE TITLE
undefined symbol: PyString_FromStringAndSize

### ISSUE THREAD

**Issue by konstin** [linkcheck/linkchecker#88]
I've installing the latest git version using pip, but I can't run it as it crashes on startup with the following error:

```
Traceback (most recent call last):
  File "/home/konsti/meine-stadt-transparent/venv/bin/linkchecker", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkchecker", line 36, in <module>
    from linkcheck.cmdline import print_version, print_usage, aggregate_url, \
  File "/home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkcheck/cmdline.py", line 23, in <module>
    from . import checker, fileutil, strformat, plugins
  File "/home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkcheck/checker/__init__.py", line 178, in <module>
    from . import (fileurl, unknownurl, ftpurl, httpurl, dnsurl,
  File "/home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkcheck/checker/ftpurl.py", line 29, in <module>
    from . import proxysupport, httpurl, internpaturl, get_index_html
  File "/home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkcheck/checker/httpurl.py", line 38, in <module>
    from ..HtmlParser import htmlsax
ImportError: /home/konsti/meine-stadt-transparent/venv/src/linkchecker/linkcheck/HtmlParser/htmlsax.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyString_FromStringAndSize
```

**Comment by anarcat** [comment]
how did you install linkchecker? which version? which operating system, version? which version of python? please provide more info, thanks.

**Comment by mgedmin** [comment]
Are you using Python 3?  We don't support Python 3 yet (see #40).

**Comment by konstin** [comment]
I'd been using python3. With python 2, everything works fine.

I've created #89 to document that problem.

**Comment by anarcat** [comment]
thanks, so i guess we do have a documentation problem. thank you for your contribution!

**Comment by KjellMorgenstern** [comment]
The issue was fixed by documenting that python3 is not yet supported. However, currently the README on the github frontpage suggests that python3 is needed, and to install with
```pip install git+https://github.com/linkchecker/linkchecker.git@v9.4.0.```

I did so on ubuntu 20.04, and got this issue again. PyString_FromStringAndSize seems to be python2 (some advises say that python3-dev is needed, but that doesn't solve the problem).

I changed the command and run this again:
```pip3 install --user git+https://github.com/linkchecker/linkchecker.git@master```

Which results in a successful update to 10.0.0.dev0
```
Collecting git+https://github.com/linkchecker/linkchecker.git@master
  Cloning https://github.com/linkchecker/linkchecker.git (to revision master) to /tmp/pip-req-build-34vyc66d
  Running command git clone -q https://github.com/linkchecker/linkchecker.git /tmp/pip-req-build-34vyc66d
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 1.8 MB/s 
Requirement already satisfied: dnspython in ./.local/lib/python3.8/site-packages (from LinkChecker==10.0.0.dev0) (1.16.0)
Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (from LinkChecker==10.0.0.dev0) (0.26)
Requirement already satisfied: requests>=2.4 in ./.local/lib/python3.8/site-packages (from LinkChecker==10.0.0.dev0) (2.14.2)
Collecting soupsieve>1.2
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Building wheels for collected packages: LinkChecker
  Building wheel for LinkChecker (setup.py) ... done
  Created wheel for LinkChecker: filename=LinkChecker-10.0.0.dev0-py3-none-any.whl size=271738 sha256=1482872f75f0560b5d583853ef7dc225f3bcb2d5cba3e7cdad71f78914511afa
  Stored in directory: /tmp/pip-ephem-wheel-cache-r8dr63ck/wheels/4e/63/e6/cc15dda001c6087ddaebb75f5358c804fdc8e8189d07359a7f
Successfully built LinkChecker
Installing collected packages: soupsieve, beautifulsoup4, LinkChecker
  Attempting uninstall: LinkChecker
    Found existing installation: LinkChecker 9.4.0
    Uninstalling LinkChecker-9.4.0:
      Successfully uninstalled LinkChecker-9.4.0
Successfully installed LinkChecker-10.0.0.dev0 beautifulsoup4-4.9.1 soupsieve-2.0.1
```

The resulting linkchecker install seems to work on ubuntu 20.04
I think to get working instructions on the front page "0.9.4" should be changed to "master" for now.

**Comment by mgedmin** [comment]
I'm sorry for the confusion.  The README is wrong: v9.4.0 is the last release that supports (and requires) Python 2 and has C extensions.  git master supports (and requires) Python 3, as you've discovered, and it has no C extensions.

The PR for fixing the readme (#362) got bogged down in bikeshedding and we kind of lost track of the current misleading state of the readme.
